# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GetirTodo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RealmSwift', '~> 10.8'

  target 'GetirTodoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GetirTodoUITests' do
    # Pods for testing
  end

end
